### ISSUE TITLE
Error During Search

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/anserini-bm25prf-docker#1]
I get the following error during search with the tuned hyper-parameters (default works fine):
```
(venv) jig@jig:~/jig$ python run.py search --repo osirrc2019/anserini-bm25prf --collection robust04 --output output/anserini-bm25prf --topic topics/topics.robust04.txt --qrels qrels/qrels.robust04.txt --opts k1=0.9 b=0.2 k1_prf=0.9 b_prf=0.6 num_new_temrs=40 num_docs=10 new_term_weight=0.1
Starting container from saved image...
Logs for search in container with ID c745809822bc3325605dd682330e003e7610cc9e040edaae6050a445b3acdcd7...
Traceback (most recent call last):
  File "/search", line 13, in <module>
    params = Bm25PRFParams(**{p:float(v) if "." in v else int(v) for p, v in opts.items()})
TypeError: __init__() got an unexpected keyword argument 'num_new_temrs'
```

Can you take a look, @matthew-z ?

**Comment by matthew-z** [comment]
This error has been fixed one or two days before...but dockerHub didn't build the latest commit (the latest one on hub was built 3 days before).... 

https://hub.docker.com/r/osirrc2019/anserini-bm25prf/builds

**Comment by matthew-z** [comment]
Sorry, I misunderstood the page https://hub.docker.com/r/osirrc2019/anserini-bm25prf/builds.

I will look into the bug.

**Comment by ryan-clancy** [comment]
> Sorry, I misunderstood the page https://hub.docker.com/r/osirrc2019/anserini-bm25prf/builds.

This is the page you want to look at the recent builds: https://hub.docker.com/r/osirrc2019/anserini-bm25prf/tags

> I will look into the bug.

Thanks!

**Comment by matthew-z** [comment]
I have fixed the typo: `num_new_temrs ` -> `num_new_terms `.....

Could you pull the latest docker and run the fixed command?

```
 python run.py search \
  --repo osirrc2019/anserini-bm25prf \
  --output out \
  --qrels qrels/qrels.robust04.txt \
  --topic topics/topics.robust04.txt \
  --collection robust04 \
  --opts k1=0.9 b=0.2 k1_prf=0.9 b_prf=0.6 num_new_terms=40 num_docs=10 new_term_weight=0.1 
```

**Comment by ryan-clancy** [comment]
Looks good now, thanks!
